"""test2

Revision ID: 9a22abf99497
Revises: 1c0367c723f4
Create Date: 2024-03-06 07:33:30.938738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a22abf99497"
down_revision: Union[str, None] = "1c0367c723f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("hashed_password", sa.String(length=1024), nullable=False)
    )
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
